const pipelines = [
  {
    length: 1800,
    outerDiameter: 58,
    innerDiameter: 47,
    glassThickness: 1.5,
    material: 'Borosilicate Glass 3.3',
    absorptionMaterial: 'AL/SS/CU',
    absorptionCoefficient: '>90%',
    glass: 'P<5x10-2Pa',
    maxTemperature: '>200',
    netWeight: 2.23,
  },
  {
    length: 2000,
    outerDiameter: 60,
    innerDiameter: 48,
    glassThickness: 1.8,
    material: 'Borosilicate Glass 3.3',
    absorptionMaterial: 'AL/SS/CU',
    absorptionCoefficient: '>92%',
    glass: 'P<5x10-2Pa',
    maxTemperature: '>250',
    netWeight: 2.5,
  },
  {
    length: 1500,
    outerDiameter: 55,
    innerDiameter: 44,
    glassThickness: 1.5,
    material: 'Borosilicate Glass 3.3',
    absorptionMaterial: 'AL/SS/CU',
    absorptionCoefficient: '>88%',
    glass: 'P<5x10-2Pa',
    maxTemperature: '>190',
    netWeight: 2.0,
  },
  {
    length: 1800,
    outerDiameter: 58,
    innerDiameter: 47,
    glassThickness: 1.6,
    material: 'Borosilicate Glass 3.3',
    absorptionMaterial: 'AL/SS/CU',
    absorptionCoefficient: '>90%',
    glass: 'P<5x10-2Pa',
    maxTemperature: '>220',
    netWeight: 2.3,
  },
];
